name: "Workflow Commands"

on: 
  push:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps: 
    - name: "group logging"
      run: |
        echo "::group::My Group Message"
        echo "Msg1"
        echo "Msg2"
        echo "::endgroup::"
    - name: "github env add"
      run: |
        echo "MY_ENV_VAL=linux-abc" >> $GITHUB_ENV
    - name: "echo env val"
      run: |
        echo $MY_ENV_VAL